version: '3'
services:
  api-gateway: 
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./services/api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./services/frontend:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - db

  service1: 
    build: ./services/backend/service1
    container_name: service1
    depends_on:
      - db
  
  service2: 
    build: ./services/backend/service2
    container_name: service2
    depends_on:
      - db
  
  db:
    image: mongo:latest
    container_name: db
    ports:
      # for local access
      - 27017:27017
    logging:
      driver: none

